version: '3.8'

services:
  youtube-downloader:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: youtube-downloader
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads #TODO: CHANGE PATH CORRECTLY
    restart: unless-stopped
