spring:
  mvc:
    async:
      request-timeout: -1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  show-actuator: true

server:
  port: ${PORT:10000}